#!/usr/bin/env python3
"""
Mann Made Media - Client Onboarding Script
Usage: python3 onboard_client.py --client clients/new-client.json [--dry-run]
"""

import argparse
import json
import os
import sys
import subprocess
from pathlib import Path
from datetime import datetime

OPENCLAW_HOME = Path.home() / ".openclaw"
BROWSER_DIR = OPENCLAW_HOME / "browser"
STARTUP_SCRIPT = BROWSER_DIR / "start-chrome-profiles.sh"
CLIENTS_DIR = Path(__file__).parent.parent / "clients"


def load_config(config_path: str) -> dict:
    p = Path(config_path)
    if not p.exists():
        print(f"ERROR: Config file not found: {config_path}")
        sys.exit(1)
    with open(p) as f:
        return json.load(f)


def create_content_folder(cfg: dict, dry_run: bool) -> str:
    folder = cfg.get("content_folder", "")
    if not folder:
        folder = str(Path.home() / f".openclaw/workspace/assets/clients/{cfg['id']}/inbox/")
    if dry_run:
        print(f"  [DRY-RUN] Would create content folder: {folder}")
    else:
        Path(folder).mkdir(parents=True, exist_ok=True)
        print(f"  Content folder ready: {folder}")
    return folder


def create_browser_profile(cfg: dict, dry_run: bool) -> str:
    user_data = BROWSER_DIR / cfg["id"] / "user-data"
    if dry_run:
        print(f"  [DRY-RUN] Would create browser profile: {user_data}")
    else:
        user_data.mkdir(parents=True, exist_ok=True)
        print(f"  Browser profile dir ready: {user_data}")
    return str(user_data)


def print_login_instructions(cfg: dict):
    port = cfg["cdp_port"]
    enabled = [p for p, v in cfg.get("platforms", {}).items() if v.get("enabled")]
    print(f"\n  === Login Instructions ===")
    print(f"  Open Chrome on port {port} and log in to: {', '.join(enabled)}")
    print(f"  Command:")
    print(f"  /Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome \\")
    print(f"    --remote-debugging-port={port} \\")
    print(f"    --user-data-dir={BROWSER_DIR}/{cfg['id']}/user-data \\")
    print(f"    --no-first-run --no-default-browser-check &")
    print(f"  ========================\n")


def update_startup_script(dry_run: bool):
    """Regenerate start-chrome-profiles.sh from all active client configs."""
    configs = []
    for f in CLIENTS_DIR.glob("*.json"):
        if f.stem == "new-client-template":
            continue
        try:
            cfg = json.loads(f.read_text())
            if cfg.get("status") == "active":
                configs.append(cfg)
        except Exception:
            pass

    lines = ["#!/bin/bash", "# Auto-generated by onboard_client.py - do not edit manually", "# Start Chrome profiles for all active Mann Made Media clients", ""]

    for cfg in sorted(configs, key=lambda c: c["cdp_port"]):
        cid = cfg["id"]
        name = cfg["name"]
        port = cfg["cdp_port"]
        user_data = f"$HOME/.openclaw/browser/{cid}/user-data"
        log_file = f"/tmp/chrome-{cid}.log"
        lines.append(f'echo "Starting {name} Chrome (port {port})..."')
        lines.append(f'/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome \\')
        lines.append(f'  --remote-debugging-port={port} \\')
        lines.append(f'  --user-data-dir="{user_data}" \\')
        lines.append(f'  --no-first-run --no-default-browser-check \\')
        lines.append(f'  > {log_file} 2>&1 &')
        lines.append('sleep 3')
        lines.append("")

    lines.append('echo "All Chrome profiles launching..."')
    lines.append("sleep 5")
    lines.append('echo "Checking ports..."')
    for cfg in sorted(configs, key=lambda c: c["cdp_port"]):
        port = cfg["cdp_port"]
        name = cfg["name"]
        lines.append(f'curl -s http://localhost:{port}/json/version > /dev/null && echo "{port} ({name}): OK" || echo "{port} ({name}): DOWN"')

    script_content = "\n".join(lines) + "\n"

    if dry_run:
        print(f"  [DRY-RUN] Would update startup script: {STARTUP_SCRIPT}")
        print(f"  Active clients to include: {[c['name'] for c in configs]}")
    else:
        STARTUP_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
        STARTUP_SCRIPT.write_text(script_content)
        STARTUP_SCRIPT.chmod(0o755)
        print(f"  Startup script updated: {STARTUP_SCRIPT}")
        print(f"  Active clients: {[c['name'] for c in configs]}")


def build_post_cron_prompt(cfg: dict, platform: str, post_time: str) -> str:
    name = cfg["name"]
    port = cfg["cdp_port"]
    pinfo = cfg["platforms"].get(platform, {})
    handle = pinfo.get("handle", "")
    queue = cfg.get("sheet_id") or cfg.get("content_folder", "")
    return (
        f"You are posting on behalf of {name} on {platform}. "
        f"ALWAYS use agent-browser --cdp {port}. "
        f"Check the content queue at {queue}. "
        f"Pick the next unposted item, post it to {platform} as {handle}, mark it as posted."
    )


def build_engage_cron_prompt(cfg: dict, platform: str) -> str:
    name = cfg["name"]
    port = cfg["cdp_port"]
    pinfo = cfg["platforms"].get(platform, {})
    handle = pinfo.get("handle", "")
    return (
        f"You are engaging on behalf of {name} on {platform}. "
        f"ALWAYS use agent-browser --cdp {port}. "
        f"Like recent posts in the feed, reply to any comments on {name}'s posts ({handle}). "
        f"Keep replies on-brand for {name}."
    )


def build_report_cron_prompt(cfg: dict) -> str:
    name = cfg["name"]
    email = cfg["reporting"].get("email", "")
    return (
        f"Generate a weekly social media performance report for {name}. "
        f"Check all platform analytics, summarize reach, engagement, and top posts. "
        f"Send the report to {email}."
    )


def create_cron_jobs(cfg: dict, dry_run: bool) -> list:
    """Create openclaw cron jobs via CLI and return list of created job IDs."""
    created = []
    client_id = cfg["id"]
    enabled_platforms = {p: v for p, v in cfg["platforms"].items() if v.get("enabled")}

    # Post crons - per platform, per post time
    for platform, pinfo in enabled_platforms.items():
        for post_time in pinfo.get("post_times", []):
            hour, minute = post_time.split(":")
            prompt = build_post_cron_prompt(cfg, platform, post_time)
            cron_name = f"{client_id}-post-{platform}-{hour}{minute}"
            cron_expr = f"{minute} {hour} * * *"

            if dry_run:
                print(f"  [DRY-RUN] Would create POST cron: {cron_name} @ {post_time} for {platform}")
                print(f"    Prompt: {prompt[:100]}...")
                created.append(f"dry-run-{cron_name}")
            else:
                result = subprocess.run(
                    ["openclaw", "cron", "add",
                     "--name", cron_name,
                     "--schedule", cron_expr,
                     "--prompt", prompt],
                    capture_output=True, text=True
                )
                if result.returncode == 0:
                    # Extract ID from output if available
                    job_id = result.stdout.strip().split()[-1] if result.stdout.strip() else cron_name
                    print(f"  Created POST cron: {cron_name} @ {post_time} for {platform}")
                    created.append(job_id)
                else:
                    print(f"  WARN: Failed to create POST cron {cron_name}: {result.stderr.strip()}")
                    created.append(f"failed-{cron_name}")

    # Engage crons - 3x daily per enabled platform
    engage_times = cfg["posting"].get("engage_times", ["10:00", "15:00", "19:00"])
    if cfg["posting"].get("engage"):
        for platform in enabled_platforms:
            for engage_time in engage_times:
                hour, minute = engage_time.split(":")
                prompt = build_engage_cron_prompt(cfg, platform)
                cron_name = f"{client_id}-engage-{platform}-{hour}{minute}"
                cron_expr = f"{minute} {hour} * * *"

                if dry_run:
                    print(f"  [DRY-RUN] Would create ENGAGE cron: {cron_name} @ {engage_time} for {platform}")
                    created.append(f"dry-run-{cron_name}")
                else:
                    result = subprocess.run(
                        ["openclaw", "cron", "add",
                         "--name", cron_name,
                         "--schedule", cron_expr,
                         "--prompt", prompt],
                        capture_output=True, text=True
                    )
                    if result.returncode == 0:
                        job_id = result.stdout.strip().split()[-1] if result.stdout.strip() else cron_name
                        print(f"  Created ENGAGE cron: {cron_name} @ {engage_time} for {platform}")
                        created.append(job_id)
                    else:
                        print(f"  WARN: Failed to create ENGAGE cron {cron_name}: {result.stderr.strip()}")
                        created.append(f"failed-{cron_name}")

    # Weekly report cron
    report = cfg.get("reporting", {})
    if report.get("email"):
        day_map = {"monday": "1", "tuesday": "2", "wednesday": "3", "thursday": "4",
                   "friday": "5", "saturday": "6", "sunday": "0"}
        day_num = day_map.get(report.get("day", "monday"), "1")
        rtime = report.get("time", "08:00")
        hour, minute = rtime.split(":")
        prompt = build_report_cron_prompt(cfg)
        cron_name = f"{client_id}-report-weekly"
        cron_expr = f"{minute} {hour} * * {day_num}"

        if dry_run:
            print(f"  [DRY-RUN] Would create REPORT cron: {cron_name} on {report.get('day')} @ {rtime}")
            created.append(f"dry-run-{cron_name}")
        else:
            result = subprocess.run(
                ["openclaw", "cron", "add",
                 "--name", cron_name,
                 "--schedule", cron_expr,
                 "--prompt", prompt],
                capture_output=True, text=True
            )
            if result.returncode == 0:
                job_id = result.stdout.strip().split()[-1] if result.stdout.strip() else cron_name
                print(f"  Created REPORT cron: {cron_name} on {report.get('day')} @ {rtime}")
                created.append(job_id)
            else:
                print(f"  WARN: Failed to create REPORT cron {cron_name}: {result.stderr.strip()}")
                created.append(f"failed-{cron_name}")

    return created


def main():
    parser = argparse.ArgumentParser(description="Onboard a new Mann Made Media client")
    parser.add_argument("--client", required=True, help="Path to client JSON config file")
    parser.add_argument("--dry-run", action="store_true", help="Preview actions without executing")
    args = parser.parse_args()

    print(f"\nMann Made Media - Client Onboarding")
    print(f"====================================")
    if args.dry_run:
        print(f"*** DRY RUN MODE - no changes will be made ***\n")

    cfg = load_config(args.client)
    print(f"Client: {cfg['name']} (id: {cfg['id']})")
    print(f"CDP Port: {cfg['cdp_port']}")
    print(f"Status: {cfg['status']}")
    print()

    # Step 1: Create content folder
    print("1. Content folder")
    content_folder = create_content_folder(cfg, args.dry_run)

    # Step 2: Create browser profile dir
    print("\n2. Browser profile")
    user_data = create_browser_profile(cfg, args.dry_run)

    # Step 3: Print login instructions
    print("\n3. Login instructions")
    print_login_instructions(cfg)

    # Step 4: Update startup script
    print("4. Updating startup script")
    update_startup_script(args.dry_run)

    # Step 5: Create cron jobs
    print("\n5. Creating cron jobs")
    created_jobs = create_cron_jobs(cfg, args.dry_run)

    # Summary
    print("\n====================================")
    print(f"Summary for {cfg['name']}")
    print(f"------------------------------------")
    print(f"Content folder: {content_folder}")
    print(f"Browser profile: {user_data}")
    print(f"CDP port: {cfg['cdp_port']}")
    enabled = [p for p, v in cfg.get("platforms", {}).items() if v.get("enabled")]
    print(f"Enabled platforms: {', '.join(enabled)}")
    print(f"Cron jobs created: {len(created_jobs)}")
    for job in created_jobs:
        print(f"  - {job}")

    if not args.dry_run:
        # Update created_at if blank
        if not cfg.get("created_at"):
            cfg["created_at"] = datetime.now().isoformat()
            with open(args.client, "w") as f:
                json.dump(cfg, f, indent=2)
            print(f"\nConfig updated with created_at timestamp.")

    print(f"\nOnboarding {'(dry run) ' if args.dry_run else ''}complete for {cfg['name']}!")


if __name__ == "__main__":
    main()
